name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      BUILD_CONFIG: Release
    steps:
      - uses: actions/checkout@v3

      - name: Install SonarCloud scanner
        run: dotnet tool update -g dotnet-sonarscanner

      - name: Begin analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: dotnet-sonarscanner begin /k:"Sergio1192_Kata-SonarCloud-Pipelines" /o:"sergio1192-github" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.vstest.reportsPaths="**/TestResults/*.trx" /d:sonar.cs.opencover.reportsPaths="**/TestResults/**/coverage.opencover.xml"

      - name: Build
        run: dotnet build -c $BUILD_CONFIG

      - name: Test
        run: dotnet test --no-build -c $(buildConfiguration) --logger trx --results-directory TestResults --collect "XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover

      - name: End analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: .
